import { getAllArticles } from '@/lib/db/storage';
import ArticleCard from './components/ArticleCard';
import Header from './components/Header';

export const revalidate = 0;

export default async function HomePage() {
  const articles = await getAllArticles();

  return (
    <div style={{ minHeight: '100vh', background: 'var(--theme-bg)', transition: 'background 0.3s ease' }}>
      <Header />

      <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '3rem 2rem' }}>
        {articles.length === 0 ? (
          <div style={{ 
            textAlign: 'center', 
            padding: '5rem 2rem',
            background: 'var(--theme-surface)',
            borderRadius: '20px',
            border: '1px solid var(--theme-border)',
            transition: 'all 0.3s ease',
          }}>
            <div style={{
              fontSize: '4rem',
              marginBottom: '1.5rem',
            }}>
              📝
            </div>
            <h2 style={{ 
              fontSize: '1.8rem', 
              color: 'var(--theme-accent)',
              marginBottom: '1rem',
              fontWeight: 600,
            }}>
              No articles yet
            </h2>
            <p style={{ fontSize: '1.1rem', color: 'var(--theme-text-secondary)', marginBottom: '1.5rem' }}>
              Generate your first article using the API!
            </p>
            <div style={{
              background: 'var(--theme-bg)',
              padding: '1.5rem',
              borderRadius: '12px',
              display: 'inline-block',
              textAlign: 'left',
              marginTop: '1rem',
              border: '1px solid var(--theme-border)',
            }}>
              <code style={{ 
                color: 'var(--theme-accent)',
                fontSize: '0.9rem',
                fontFamily: 'monospace',
              }}>
                POST /api/generate-article
              </code>
            </div>
          </div>
        ) : (
          <>
            <div style={{
              textAlign: 'center',
              marginBottom: '3rem',
            }}>
              <h2 style={{
                fontSize: '2.5rem',
                color: 'var(--theme-text)',
                fontWeight: 600,
                marginBottom: '0.5rem',
              }}>
                Latest Articles
              </h2>
              <p style={{ color: 'var(--theme-text-secondary)', fontSize: '1.1rem' }}>
                {articles.length} {articles.length === 1 ? 'article' : 'articles'} generated by AI
              </p>
            </div>
            
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
              gap: '2.5rem',
              marginBottom: '3rem'
            }}>
              {articles.map((article) => (
                <ArticleCard
                  key={article.id}
                  slug={article.slug}
                  title={article.title}
                  description={article.description}
                  author={article.author}
                  readingTime={article.reading_time}
                  tags={article.tags}
                  image={article.image}
                />
              ))}
            </div>
          </>
        )}
      </main>

      <footer style={{
        padding: '2rem',
        textAlign: 'center',
        borderTop: '1px solid var(--theme-border)',
        color: 'var(--theme-text-secondary)',
        fontSize: '0.9rem',
      }}>
        <p>© {new Date().getFullYear()} Uplix. All rights reserved.</p>
      </footer>
    </div>
  );
}
