import { getAllArticles } from '@/lib/db/storage';
import ArticleCard from './components/ArticleCard';

export const revalidate = 0;

export default async function HomePage() {
  const articles = await getAllArticles();

  return (
    <div style={{ minHeight: '100vh' }}>
      <header style={{ 
        background: 'linear-gradient(135deg, #1CB76D 0%, #0a9f5a 100%)',
        padding: '4rem 2rem',
        textAlign: 'center',
        boxShadow: '0 4px 20px rgba(28, 183, 109, 0.2)',
      }}>
        <div style={{ maxWidth: '900px', margin: '0 auto' }}>
          <h1 style={{ 
            fontSize: '3.5rem', 
            marginBottom: '1.25rem',
            color: 'white',
            fontWeight: 700,
            textShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
          }}>
            AI-Powered Blog
          </h1>
          <p style={{ 
            fontSize: '1.3rem', 
            color: 'rgba(255, 255, 255, 0.95)',
            fontWeight: 300,
            lineHeight: 1.6,
          }}>
            Discover cutting-edge articles written by advanced AI technology
          </p>
        </div>
      </header>

      <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '3rem 2rem' }}>
        {articles.length === 0 ? (
          <div style={{ 
            textAlign: 'center', 
            padding: '5rem 2rem',
            background: 'white',
            borderRadius: '20px',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
          }}>
            <div style={{
              fontSize: '4rem',
              marginBottom: '1.5rem',
            }}>
              📝
            </div>
            <h2 style={{ 
              fontSize: '1.8rem', 
              color: '#1CB76D',
              marginBottom: '1rem',
              fontWeight: 600,
            }}>
              No articles yet
            </h2>
            <p style={{ fontSize: '1.1rem', color: '#666', marginBottom: '1.5rem' }}>
              Generate your first article using the API!
            </p>
            <div style={{
              background: '#f8f9fa',
              padding: '1.5rem',
              borderRadius: '12px',
              display: 'inline-block',
              textAlign: 'left',
              marginTop: '1rem',
            }}>
              <code style={{ 
                color: '#1CB76D',
                fontSize: '0.9rem',
                fontFamily: 'monospace',
              }}>
                POST /api/generate-article
              </code>
            </div>
          </div>
        ) : (
          <>
            <div style={{
              textAlign: 'center',
              marginBottom: '3rem',
            }}>
              <h2 style={{
                fontSize: '2.5rem',
                color: '#1a1a1a',
                fontWeight: 600,
                marginBottom: '0.5rem',
              }}>
                Latest Articles
              </h2>
              <p style={{ color: '#666', fontSize: '1.1rem' }}>
                {articles.length} {articles.length === 1 ? 'article' : 'articles'} generated by AI
              </p>
            </div>
            
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
              gap: '2.5rem',
              marginBottom: '3rem'
            }}>
              {articles.map((article) => (
                <ArticleCard
                  key={article.id}
                  slug={article.slug}
                  title={article.title}
                  description={article.description}
                  author={article.author}
                  readingTime={article.reading_time}
                  tags={article.tags}
                  image={article.image}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
